import { game } from "@prisma/client";
import { useQuery } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import {useState, useEffect } from "react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const [games,setGames] = useState<game[]>()
  const queryAllGame = api.game.getAll.useQuery();
  const mutationCreateGame = api.game.create.useMutation();
  
  const createGame = async (name: string) => {
    await mutationCreateGame.mutate({name}, {
      onSettled(data, variables, context) {
        if (data) {
          const current = games;
          current?.push(data);
          setGames(current);
        }
      },
    })
  }

  useEffect(() => {
    if (queryAllGame.isSuccess) {
      setGames(queryAllGame.data);
    }
  }, [queryAllGame.isSuccess]);
  

  return (
    <>
      <Head>
        <title>Scrambled Eggs: Web</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="flex flex-row bg-gradient-to-b from-[#2e026d] to-[#15162c] p-10">
          <div className="mr-8">
            {games?.map((item: { name: string }) => <p>{item.name}</p>)}
          </div>
          <button type="button" className="bg-slate-400 p-2 radius-2"onClick={() => createGame("test")}>Create!</button>
        </div>
      </main>
    </>
  );
};

export default Home;
